;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        sp-backward-delete-char
        whole-line-or-region-yank
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        helm-M-x
        helm-find-files
        ))
