;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        crux-smart-open-line
        dakra-upcase-dwim
        electric-newline-and-maybe-indent
        haml-electric-backspace
        helm-show-kill-ring
        indent-for-tab-command
        ledger-magic-tab
        markdown-exdent-or-delete
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        outshine-self-insert-command
        selected-off
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        sp-splice-sexp
        whole-line-or-region-yank
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        helm-M-x
        helm-find-files
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/skip-to-previous-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        js2-refactor-hydra/body
        js2-refactor-hydra/js2r-extract-var-and-exit
        js2-refactor-hydra/js2r-rename-var-and-exit
        smart-region
        ))
