;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        crux-smart-open-line
        electric-newline-and-maybe-indent
        helm-show-kill-ring
        org-delete-char
        org-self-insert-command
        sp-backward-delete-char
        whole-line-or-region-yank
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        helm-M-x
        helm-find-files
        smart-region
        ))
